#!/bin/sh

# Dependencies:
#   - mpv
#   - btfs (btplay)

baseurl="https://1337x.to"

cachedir="$HOME/.cache/notflix"
searchhtmlfile="$cachedir/search.html"
detailshtmlfile="$cachedir/details.html"
titlefile="$cachedir/titles.txt"
seedleechfile="$cachedir/seedleech.txt"
sizesfile="$cachedir/sizes.txt"
sizefilewlinenums="$cachedir/sizewlinenums.txt"
linksfile="$cachedir/links.txt"

read_query() {
	# Argument given
	test -z "$QUERY" || return 0

  echo "Search Torrent: "
  read QUERY

  # Canceled
  test -z "$QUERY" && return 1

  echo "Searching for: $QUERY"

  return 0
}

get_torrents_list() {
  # Download search results
  curl -s "$baseurl/search/$(echo $QUERY | sed 's/ /+/g')/1/" > "$searchhtmlfile"

  # Get Titles
  grep -o '<a href="/torrent/.*</a>' "$searchhtmlfile" |
    sed 's/<[^>]*>//g' |
    sed 's/\./ /g; s/\-/ /g' |
    sed 's/[^A-Za-z0-9 ]//g' |
    tr -s " " > "$titlefile"

  result_count=$(wc -l "$titlefile" | awk '{print $1}')
  if [ "$result_count" -lt 1 ]; then
    echo "😔 No Result found. Try again 🔴"
    return 1
  fi

  # Seeders and Leechers
  grep -o '<td class="coll-2 seeds.*</td>\|<td class="coll-3 leeches.*</td>' "$searchhtmlfile" |
    sed 's/<[^>]*>//g' |
    sed 'N;s/\n/ /' |
    awk '{print "[S:"$1 ", L:"$2"]" }' > "$seedleechfile"

  # Size
  grep -o '<td class="coll-4 size.*</td>' "$searchhtmlfile" |
    sed 's/<span class="seeds">.*<\/span>//g' |
    sed -e 's/<[^>]*>//g' > "$sizesfile"

  # Line numbers
  nl -w1 -s": " $sizesfile >$sizefilewlinenums

  # Links
  grep -Eo "/torrent\/[0-9]{7}\/[a-zA-Z0-9?%-]*/" "$searchhtmlfile" > "$linksfile" 2>/dev/null

  return 0
}

select_torrent_url() {
  # Getting the line number
  paste -d '@' "$sizefilewlinenums" "$seedleechfile" "$titlefile" | sed 's/@/ - /g'
  read LINE

  if [ -z "$LINE" ]; then
    return 1
  fi

  movieurl="${baseurl}$(head -n $LINE "$linksfile" | tail -n +$LINE)"

  return 0
}

get_magnet_from_movieurl() {
  echo "Reading $movieurl"
  magnet=$(curl -s "$movieurl" | grep -Po "magnet:\?xt=urn:btih:[a-zA-Z0-9]*" | head -n 1)
}

open_magnet_link() {
  if [ -z "$magnet" ]; then
  	echo "🧲 Magnet not found!"
    echo "🧲 Magnet not found!"
    return 1
  fi

  echo "🧲 Magnet found! Loading..."

  BTPLAY_FLAGS="-p mpv"

  if [ -t 0 ]; then
    btplay $BTPLAY_FLAGS "$magnet"
  else
    x-terminal-emulator -T Notflix -e bash -i -c "btplay $BTPLAY_FLAGS \"$magnet\""
  fi

  return 0
}

# Read args
QUERY="$@"

mkdir -p "$cachedir"

while :; do
  read_query || exit 0
  get_torrents_list && select_torrent_url && get_magnet_from_movieurl && open_magnet_link && exit 0
done

