#!/bin/sh

# Dependencies - peerflix, mpv

menu="dmenu -i -l 20"
baseurl="https://1337x.wtf"

cachedir="$HOME/.cache/notflix"
searchhtmlfile="$cachedir/search.html"
detailshtmlfile="$cachedir/details.html"
titlefile="$cachedir/titles.txt"
seedleechfile="$cachedir/seedleech.txt"
sizesfile="$cachedir/sizes.txt"
linksfile="$cachedir/links.txt"

query=`(test -z "$@" && $menu -p "Search Torrent: " <&- || echo "$@") | sed 's/ /+/g'`

# Canceled
test -z "$query" && exit 0

mkdir -p "$cachedir"

# Download search results
curl -s "$baseurl/search/$query/1/" > "$searchhtmlfile"

# Get Titles
grep -o '<a href="/torrent/.*</a>' "$searchhtmlfile" |
  sed 's/<[^>]*>//g' |
  sed 's/\./ /g; s/\-/ /g' |
  sed 's/[^A-Za-z0-9 ]//g' |
  tr -s " " > "$titlefile"

result_count=$(wc -l "$titlefile" | awk '{print $1}')
if [ "$result_count" -lt 1 ]; then
  notify-send "😔 No Result found. Try again 🔴"
  exit 0
fi

# Seeders and Leechers
grep -o '<td class="coll-2 seeds.*</td>\|<td class="coll-3 leeches.*</td>' "$searchhtmlfile" |
  sed 's/<[^>]*>//g' |
  sed 'N;s/\n/ /' |
  awk '{print "[S:"$1 ", L:"$2"]" }' > "$seedleechfile"

# Size
grep -o '<td class="coll-4 size.*</td>' "$searchhtmlfile" |
  sed 's/<span class="seeds">.*<\/span>//g' |
  sed -e 's/<[^>]*>//g' > "$sizesfile"

# Links
grep -Eo "/torrent\/[0-9]{7}\/[a-zA-Z0-9?%-]*/" "$searchhtmlfile" > "$linksfile"

# Getting the line number
LINE=$(expr "$(paste -d '@' "$sizesfile" "$seedleechfile" "$titlefile" |
  sed 's/@/ - /g' |
  $menu -r -ix) + 1" | bc)

movieurl="${baseurl}$(head -n $LINE "$linksfile" | tail -n +$LINE)"
echo $movieurl
magnet=$(curl -s "$movieurl" | grep -Po "magnet:\?xt=urn:btih:[a-zA-Z0-9]*" | head -n 1)

if [ -z "$magnet" ]; then
  notify-send "🧲 Magnet not found!"
  exit 1
fi

notify-send "🧲 Magnet found! Loading..."

PEERFLIX_FLAGS="-l --mpv -- --fs"

test -t 0 && \
  peerflix "$magnet" $PEERFLIX_FLAGS || \
  x-terminal-emulator -T Notflix -e bash -i -c "peerflix \"$magnet\" $PEERFLIX_FLAGS"
